### ISSUE TITLE
Количество активных обращений

### ISSUE THREAD

**Issue by imiasnikov** [getmentor/getmentor-bot#1]
As mentor
Menti information – the count of active requests to mentors.
I would like not to consider "machine gunners" (even if this particular one is not like that).
Acquaintance and immersion in the problem wastes time, and then, as a result, the meeting does not happen :(

**Comment by glamcoder** [comment]
this won't be implemented. we think the amount of requests should not influence one's decision to mentor or not. people are unique and for one person one mentor or another might provide different results, therefore we see no issue in people asking for help from multiple mentors.
on the other hand, we limited the amount pf requests one can make and it is not 5 per day
